In [1]:
# Задание 1
# Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
# Определите какому фильму было выставлено больше всего оценок 5.0.
import pandas as pd

data = pd.read_csv('ratings.csv')

data_rating_5 = data[ (data['rating'] == 5.0) ]
data_rating_5.groupby('movieId').count().sort_values(by='rating', ascending=False).head()

         userId  rating  timestamp
movieId
318       48762   48762      48762
296       37458   37458      37458
356       32009   32009      32009
260       31385   31385      31385
593       30280   30280      30280

In [16]:
# Задание 2
# По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 
# за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

power = pd.read_csv('power.csv')
power.head(10)

filtered_countries = power[ (power['country']=='Estonia') | (power['country']=='Latvia') | (power['country']=='Lithuania')]
# power_1 = power[power.quantity> 0] 

power_1 = filtered_countries[filtered_countries.quantity>=0]
power_1['quantity'].count()

26743

In [22]:
# Задание 3
# Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
# Примеры страниц (необязательно брать именно эти): 
# https://fortrader.org/quotes
# https://www.finanz.ru/valyuty/v-realnom-vremeni

pd.read_html('https://fortrader.org/quotes')[1]

,Type,Last,Chg.,Chg.%,Time
0,ВТБ Акции ОАО ВТБ,0.03815,-0.00056,-1.44665,NaN
1,Газпром Акции газпрома,229.50000,-3.28,-1.41000,NaN
2,Лукоил Акции Лукойл,5179.00000,-102.5,-1.90000,NaN
3,Роснефть Акции Роснефти,406.50000,-0.30,-0.07000,NaN
4,Сбербанк Акции Сбербанка,220.03000,+0.11,0.05000,NaN
5,Сургутнефтегаз Акции Сургутнефтегаза,25.61000,-0.010,-0.03900,NaN
6,Норникель Акции Норникель,15438.00000,-18,-0.00000,NaN
7,Аэрофлот Акции Аерофлота,108.80000,+11.99,12.39000,NaN
8,Северсталь Акции Северсталь,943.60000,-2.6,-0.30000,NaN
9,Транснефть Акции транснефти,145450.00000,-20 850,-13.00000,NaN
10,Ростелеком Курс акций ростелекома,81.00000,+8.17,11.22000,NaN
11,RUSAL акции RUSAL,3.15000,+0.01,0.32000,NaN